### ISSUE TITLE
Test of issue part at Github

### ISSUE THREAD

**Issue by HuubMons** [HuubMons/HuMo-genealogy#23]
Test of issue part at Github

**Comment by Barcha17** [comment]
Maybe you need to open a dev branch?

**Comment by HuubMons** [comment]
Hi,

First: thanks for all changes!

*>Maybe you need to open a dev branch?*
That's probably better, I am still beginner using Github.
I will try to add a dev branch and add all changes.

Huub.


Op vr 12 mei 2023 om 15:50 schreef Barcha17 ***@***.***>:

**Comment by Barcha17** [comment]
It's a pleasure, I appreciate your feedback
