### ISSUE TITLE
Change media/picture priority (blue arrows) doesn't work in relationship view

### ISSUE THREAD

**Issue by Gawrion** [HuubMons/HuMo-genealogy#49]
In normal person view these blue arrows work - i can rearrange media.

In relationship (marriage) view it doesn't work.

It's not critical - im just reporting as i noticed it now.

**Comment by HuubMons** [comment]
In some cases the ordering system messes up.
Could you check of the ordering numbers are ok?
- Place mouse at first arrow. Check if you see in link: "event_down=1". There should be only 1 arrow down.
- Check second arrow. Check if you see in link: even_down=2 or event_up=2.
- Check other lines. Line 3 should be 3 etc.

If the numbering failes, it is possible to restore this by clicking the proper arrow (try to restore numbering).
Or: let me know, it's better to build a order number check.

I actually want to replace all arrow ordering items (in all pages) by the same system as the children ordering system. But it's at the my quit long wish list I made.

**Comment by Gawrion** [comment]
In relation i have 2 photos.
First arrow link: https://devgene2.tots.pl/admin/index.php?page=editor&event_down=1&event_connect_kind=family&event_kind=picture&dummy=11#picture

Second arrow link: https://devgene2.tots.pl/admin/index.php?page=editor&event_up=2&event_connect_kind=family&event_kind=picture&dummy=12#picture

When i click page reloads and order is the same. No debug warnings. No changes in database table. When i manually change order in DB it changes. 
Drag and drop would be nicer aproach.

**Comment by Gawrion** [comment]
I repaired it - code was missing 6 lines ;)
https://github.com/HuubMons/HuMo-genealogy/commit/3cb77793080e7951ceb28af3416f59b0dadcb851

**Comment by HuubMons** [comment]
Perfect!

I will mark this as solved.
I will check drag and drop, I allready wanted this a long time.
