### ISSUE TITLE
Bug. Deprecated. New tree added and go to homepage for user.

### ISSUE THREAD

**Issue by Gawrion** [HuubMons/HuMo-genealogy#58]
### Reproduce: 

When adding new tree (BEZ NAZWY on screen) and going to homepage choosing that tree gives a lot of Deprecated notices for show_tree_date.php

### Branch
prepare_next_version

ps. I will put bugs n here so we can manage it. U can categorize them.

![Zrzut ekranu 2024-12-07 120549](https://github.com/user-attachments/assets/ff22f525-fdf2-4d9f-accc-7390878a4a53)
![Zrzut ekranu 2024-12-07 120606](https://github.com/user-attachments/assets/dc2a3641-8001-4d7b-820f-1e748fff2135)

**Comment by HuubMons** [comment]
This problem is solved, will be added in the prepare_next_version.
Thanks!
