### ISSUE TITLE
Bug. Fatal error. When logged as editor but not admin.

### ISSUE THREAD

**Issue by Gawrion** [HuubMons/HuMo-genealogy#64]
### Reproduce

Login to account which can edit but is not admin. Go through a link "admin" in menu. U should get this fatal error:
![Screenshot_40](https://github.com/user-attachments/assets/d55300ba-6bb9-4825-8754-4ccbe7ce3e1a)

**Comment by HuubMons** [comment]
Ah, I didn't notice this problem yet. This is solved in prepare_next_version branch.
