### ISSUE TITLE
Bug. Warning. When adding relation to person in tree

### ISSUE THREAD

**Issue by Gawrion** [HuubMons/HuMo-genealogy#65]
### Reproduce

I added one person in new tree. Then was trying to add relation (new person). I got this warning:
![Screenshot_39](https://github.com/user-attachments/assets/20668790-153a-4d1a-aa73-252063534469)

**Comment by HuubMons** [comment]
Thanks for mentioning this bug! For some reason I missed these errors.
I have solved this, will be added to Github with next push.
