### ISSUE TITLE
Bug. Fatal error. My family colaborator sent mi this today.

### ISSUE THREAD

**Issue by Gawrion** [HuubMons/HuMo-genealogy#67]
### Reproduce

He was trying to go to person edit. I asked him what user agent he has and i'm waiting forr feedback. It seems too short datatype is in database column.

`Fatal error: Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'stat_user_agent' at row 1 in /var/www/gene-tots/views/family.php:367 Stack trace: #0 /var/www/gene-tots/views/family.php(367): PDO->query() #1 /var/www/gene-tots/views/layout.php(771): require('...') #2 /var/www/gene-tots/index.php(572): include_once('...') #3 {main} thrown in /var/www/gene-tots/views/family.php on line 367`

**Comment by HuubMons** [comment]
This problem is solved! And added to pnv branch.
